---
version: "3"

services:
  terminal_sync:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "terminal_sync:latest"
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/${TERMSYNC_JSON_LOG_DIR}
      - ./terminal_sync.log:/app/terminal_sync.log
    entrypoint: "python3 -m terminal_sync"
