---
version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: terminal_sync:latest
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./terminal_sync.log:/app/terminal_sync.log
